name: Distro and LVM tests

on:
  push:
    branches:
    - main
    - ci-macos-fix
  pull_request:
  schedule:
    - cron: '17 20 * * *'

jobs:
  vagrant:
    strategy:
      matrix:
        vagrant_target:
          - debian
          - debianrustup
          - debianlvm
          - rocky9
          - fedora33
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3

      - name: Start vagrant box
        run: vagrant up ${{ matrix.vagrant_target }}
