name: Distro and LVM tests

on:
  push:
    branches:
    - main
  pull_request:
  schedule:
    - cron: '17 20 * * *'

jobs:
  vagrant:
    strategy:
      matrix:
        vagrant_target:
          - debian
          - debianrustup
          - debianlvm
          - rocky9
          - fedora33
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Parallels
        run: |
         curl -o parallels.dmg $PARALLELS_DMG_URL
         hdiutil attach parallels.dmg
         sudo cp -R "/Volumes/Parallels Desktop "*"/Parallels Desktop.app" /Applications
         hdiutil unmount "/Volumes/Parallels Desktop "*

      - name: Start vagrant box
        run: |
          vagrant plugin install vagrant-parallels
          vagrant up --provider parallels ${{ matrix.vagrant_target }}
