name: Distro and LVM tests

on:
  push:
    branches:
    - main
  pull_request:
  schedule:
    - cron: '17 20 * * *'

jobs:
  vagrant:
    strategy:
      matrix:
        vagrant_target:
          - debian
          - debianrustup
          - debianlvm
          - rocky9
          - fedora33
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Start vagrant box
        run: |
          vagrant plugin install vagrant-parallels
          vagrant up --provider parallels ${{ matrix.vagrant_target }}
